spring:
  application:
    name: underfloor-heating-calculator

  datasource:
    url: jdbc:postgresql://localhost:5432/heating_calculator
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 hours

calculation:
  defaults:
    pipe-spacing-cm: 15
    pipe-diameter-mm: 16
    loop-max-length-m: 100
    room-height-m: 2.5
